name: clean_settings_nnbd
description: Null safety version of clean_settings package. Settings UI generator with sane defaults. Removes the need for boilerplate code and provides a rich set of highly opinionated widgets.
version: 0.1.0
homepage: https://github.com/mzdm/clean_settings

environment:
  sdk: ">=2.12.0-259.9.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
