name: clean_settings_nnbd
description: Settings UI generator with sane defaults. Null safety version of the clean_settings package.
version: 0.2.0
homepage: https://github.com/mzdm/clean_settings_nnbd

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
